# Generated by Django 5.2.5 on 2026-08-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('', '--- انتخاب شهر ---'), ('تهران', 'تهران'), ('مشهد', 'مشهد'), ('اصفهان', 'اصفهان'), ('کرج', 'کرج'), ('شیراز', 'شیراز'), ('تبریز', 'تبریز'), ('قم', 'قم')], default='', max_length=50, verbose_name='شهر'),
        ),
    ]
