# Generated by Django 5.2.5 on 2026-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(choices=[('SUP', 'پشتیبانی'), ('SUG', 'پیشنهاد'), ('CRT', 'انتقاد')], default='SUP')),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
