# Generated by Django 5.2.5 on 2026-08-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fullname',
            field=models.CharField(blank=True, null=True),
        ),
    ]
