# Generated by Django 5.2.5 on 2026-08-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_myuser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
